version: '3'

services:
  redis-bench:
    image: "redis:alpine"
    container_name: redis-bench
    depends_on:
      - redis
    command: >
      /bin/sh -c "
        while ! nc -z redis 6379; do
          echo redis is not healthy yet...;
          sleep 1;
        done;
        echo redis is up;
        redis-benchmark -h redis;
      "
