scrape_configs:
- job_name: prometheus

  # Override the global default and scrape targets from this job every 5 seconds.
  scrape_interval: 10s

  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.

  static_configs:
    - targets: ['prometheus:9090','cadvisor:8080','node-exporter:9100', 'redis-exporter:9121']
