version: '3'

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    expose: [6379]
    ports: [6379:6379]

  web:
    image: redis_test
    container_name: web
    depends_on:
      - redis
    ports:
      - "5000:5000"

