// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.hello.proto

#ifndef PROTOBUF_test_2ehello_2eproto__INCLUDED
#define PROTOBUF_test_2ehello_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace test {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_test_2ehello_2eproto();
void protobuf_AssignDesc_test_2ehello_2eproto();
void protobuf_ShutdownFile_test_2ehello_2eproto();

class hello;
class MyRequest;
class MyResponse;

// ===================================================================

class hello : public ::google::protobuf::Message {
 public:
  hello();
  virtual ~hello();
  
  hello(const hello& from);
  
  inline hello& operator=(const hello& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const hello& default_instance();
  
  void Swap(hello* other);
  
  // implements Message ----------------------------------------------
  
  hello* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const hello& from);
  void MergeFrom(const hello& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // required string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  
  // @@protoc_insertion_point(class_scope:test.hello)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_name();
  inline void clear_has_name();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* name_;
  ::google::protobuf::int32 id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_test_2ehello_2eproto();
  friend void protobuf_AssignDesc_test_2ehello_2eproto();
  friend void protobuf_ShutdownFile_test_2ehello_2eproto();
  
  void InitAsDefaultInstance();
  static hello* default_instance_;
};
// -------------------------------------------------------------------

class MyRequest : public ::google::protobuf::Message {
 public:
  MyRequest();
  virtual ~MyRequest();
  
  MyRequest(const MyRequest& from);
  
  inline MyRequest& operator=(const MyRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MyRequest& default_instance();
  
  void Swap(MyRequest* other);
  
  // implements Message ----------------------------------------------
  
  MyRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MyRequest& from);
  void MergeFrom(const MyRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 req_id = 1;
  inline bool has_req_id() const;
  inline void clear_req_id();
  static const int kReqIdFieldNumber = 1;
  inline ::google::protobuf::int32 req_id() const;
  inline void set_req_id(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:test.MyRequest)
 private:
  inline void set_has_req_id();
  inline void clear_has_req_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 req_id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_test_2ehello_2eproto();
  friend void protobuf_AssignDesc_test_2ehello_2eproto();
  friend void protobuf_ShutdownFile_test_2ehello_2eproto();
  
  void InitAsDefaultInstance();
  static MyRequest* default_instance_;
};
// -------------------------------------------------------------------

class MyResponse : public ::google::protobuf::Message {
 public:
  MyResponse();
  virtual ~MyResponse();
  
  MyResponse(const MyResponse& from);
  
  inline MyResponse& operator=(const MyResponse& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MyResponse& default_instance();
  
  void Swap(MyResponse* other);
  
  // implements Message ----------------------------------------------
  
  MyResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MyResponse& from);
  void MergeFrom(const MyResponse& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 res_id = 1;
  inline bool has_res_id() const;
  inline void clear_res_id();
  static const int kResIdFieldNumber = 1;
  inline ::google::protobuf::int32 res_id() const;
  inline void set_res_id(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:test.MyResponse)
 private:
  inline void set_has_res_id();
  inline void clear_has_res_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 res_id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_test_2ehello_2eproto();
  friend void protobuf_AssignDesc_test_2ehello_2eproto();
  friend void protobuf_ShutdownFile_test_2ehello_2eproto();
  
  void InitAsDefaultInstance();
  static MyResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// hello

// required int32 id = 1;
inline bool hello::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void hello::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void hello::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void hello::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 hello::id() const {
  return id_;
}
inline void hello::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// required string name = 2;
inline bool hello::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void hello::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void hello::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void hello::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& hello::name() const {
  return *name_;
}
inline void hello::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void hello::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void hello::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* hello::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* hello::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// MyRequest

// required int32 req_id = 1;
inline bool MyRequest::has_req_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MyRequest::set_has_req_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MyRequest::clear_has_req_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MyRequest::clear_req_id() {
  req_id_ = 0;
  clear_has_req_id();
}
inline ::google::protobuf::int32 MyRequest::req_id() const {
  return req_id_;
}
inline void MyRequest::set_req_id(::google::protobuf::int32 value) {
  set_has_req_id();
  req_id_ = value;
}

// -------------------------------------------------------------------

// MyResponse

// required int32 res_id = 1;
inline bool MyResponse::has_res_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MyResponse::set_has_res_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MyResponse::clear_has_res_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MyResponse::clear_res_id() {
  res_id_ = 0;
  clear_has_res_id();
}
inline ::google::protobuf::int32 MyResponse::res_id() const {
  return res_id_;
}
inline void MyResponse::set_res_id(::google::protobuf::int32 value) {
  set_has_res_id();
  res_id_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace test

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_test_2ehello_2eproto__INCLUDED
