apiVersion: v1
kind: Service
metadata:
  name: adminer
spec:
  type: NodePort
  ports:
  - port: 8070       # Inner cluster port
    targetPort: 8080 # Inner backend app port at 8080
    nodePort: 30001   # External cluster port
  selector:
    app: adminer
  # clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  # Inner dns name
  name: adminer
spec:
  selector:
    matchLabels:
      app: adminer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - image: adminer:latest
        name: adminer
        ports:
        - containerPort: 8080
          name: adminer
